import type { Metadata } from "next";
import { STATIC_PREVIEW_VERSIONS } from "@/lib/brand-versions";
import type { Faction, Region, Ruleset } from "@/lib/game";
import type { GuildVersion } from "@/lib/game-versions";
import { tabardKey } from "@/lib/tabard/config";
import { guildLook, isOrderLook, type LookColumns } from "@/lib/tabard/look";

/** Static brand sets under public/brand (generated by `pnpm brand:assets`). */
export type Brand = "osm" | "guildbook";

/**
 * Where a site's icons and link preview live: a static set under public/brand, or a guild's generated set at
 * /api/brand/{slug}, versioned by its tabard so a new design busts caches.
 */
export interface BrandAssets {
  dir: string;
  version: string | null;
  ogAlt: string;
}

const OG_ALT: Record<Brand, string> = {
  osm: "El tabardo de la Order of Saint Michael, un estandarte carmesí con borde dorado y cruz blanca, junto a las palabras Order of Saint Michael, Quis ut Deus.",
  guildbook:
    "La marca de Guildbook, un libro dorado abierto con una cinta carmesí, junto a las palabras Guildbook, guild sites for World of Warcraft: Forever, sobre tres estandartes de hermandad y guildbook.io.",
};

export function staticBrand(brand: Brand): BrandAssets {
  return { dir: `/brand/${brand}`, version: null, ogAlt: OG_ALT[brand] };
}

/** The Order keeps its static tabard set; other guilds get icons generated from their tabard. */
export function guildBrand(guild: { slug: string; name: string } & LookColumns): BrandAssets {
  if (isOrderLook(guild)) return staticBrand("osm");
  return {
    dir: `/api/brand/${guild.slug}`,
    version: tabardKey(guildLook(guild).tabard),
    ogAlt: `El tabardo de ${guild.name} junto al nombre de la hermandad.`,
  };
}

const assets = (b: Brand | BrandAssets) => (typeof b === "string" ? staticBrand(b) : b);

/** The URL of one brand file, e.g. `brandFile(b, "icon-192.png")`. */
export function brandFile(b: Brand | BrandAssets, file: string) {
  const a = assets(b);
  return `${a.dir}/${file}${a.version ? `?v=${a.version}` : ""}`;
}

export function brandIcons(b: Brand | BrandAssets): NonNullable<Metadata["icons"]> {
  return {
    icon: [
      { url: brandFile(b, "icon.svg"), type: "image/svg+xml" },
      { url: brandFile(b, "favicon.ico"), sizes: "48x48" },
    ],
    apple: brandFile(b, "apple-icon.png"),
  };
}

type StaticPreview = keyof typeof STATIC_PREVIEW_VERSIONS;

const PREVIEW_ALT: Record<StaticPreview, string> = {
  guildbook: OG_ALT.guildbook,
  vigil: "El icono de Vigil, un ojo dorado sobre fondo carmesí, junto a las palabras Vigil, the combat log companion, every pull reviewed on your guild's Guildbook.",
};

/** A static link preview on the apex, versioned by its content hash (written by `pnpm brand:assets`). */
export function brandPreviewImage(preview: StaticPreview) {
  return { url: `/brand/${preview}/og.png?v=${STATIC_PREVIEW_VERSIONS[preview]}`, width: 1200, height: 630, alt: PREVIEW_ALT[preview] };
}

/** Guild pages whose link previews carry the page title above the guild's name. */
export const PREVIEW_PAGES = { charter: "Reglamento", lore: "Historia", roster: "Plantilla", progression: "Progreso", apply: "Únete" } as const;
export type PreviewPage = keyof typeof PREVIEW_PAGES;
export const isPreviewPage = (p: string | null): p is PreviewPage => p !== null && Object.hasOwn(PREVIEW_PAGES, p);

/** The guild columns a link preview draws. Region, ruleset and verification are optional. */
export interface PreviewGuild extends LookColumns {
  slug: string;
  name: string;
  motto: string | null;
  region?: Region | null;
  faction: Faction | null;
  ruleset?: Ruleset | null;
  /** Absent or WoW: Forever draws no game version. */
  gameVersion?: GuildVersion | null;
  realmSlug?: string | null;
  recruitmentOpen: boolean;
  verifiedAt?: Date | null;
}

/** Bump when the preview's design changes, so cached images are refetched. */
const PREVIEW_DESIGN = 3;

/** 32-bit FNV-1a, base 36: short and stable, and works in any runtime. */
function shortHash(s: string) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 0x01000193);
  return (h >>> 0).toString(36);
}

/** A version for a guild's link preview: changes whenever anything the image shows changes. */
export function previewVersion(guild: PreviewGuild, host: string) {
  const look = guildLook(guild);
  const art = isOrderLook(guild) ? "order" : [tabardKey(look.tabard), look.base, JSON.stringify(look.overrides)].join("/");
  return shortHash(
    [
      PREVIEW_DESIGN,
      art,
      guild.name,
      guild.motto ?? "",
      guild.region ?? "",
      guild.faction ?? "",
      guild.ruleset ?? "",
      guild.recruitmentOpen,
      Boolean(guild.verifiedAt),
      host,
      // Only other versions add to the key, so WoW: Forever previews keep their cached URLs.
      ...(guild.gameVersion && guild.gameVersion !== "forever" ? [guild.gameVersion, guild.realmSlug ?? ""] : []),
    ].join("|"),
  );
}

/** A guild's 1200 by 630 link preview at /api/brand/{slug}/og.png, drawn for its public `host`. */
export function guildPreviewImage(guild: PreviewGuild, host: string, page?: PreviewPage) {
  const query = new URLSearchParams({ v: previewVersion(guild, host) });
  if (page) query.set("page", page);
  const alt = isOrderLook(guild)
    ? "El tabardo de la Order of Saint Michael, un estandarte carmesí con borde dorado y cruz blanca, junto a las palabras Order of Saint Michael, Quis ut Deus."
    : `El tabardo de ${guild.name} junto al nombre de la hermandad${guild.motto ? ` y su lema, ${guild.motto}` : ""}.`;
  return { url: `/api/brand/${guild.slug}/og.png?${query}`, width: 1200, height: 630, alt };
}

export function brandManifestIcons(b: Brand | BrandAssets) {
  return [
    { src: brandFile(b, "icon-192.png"), sizes: "192x192", type: "image/png", purpose: "any" as const },
    { src: brandFile(b, "icon-512.png"), sizes: "512x512", type: "image/png", purpose: "any" as const },
    { src: brandFile(b, "icon-maskable-512.png"), sizes: "512x512", type: "image/png", purpose: "maskable" as const },
  ];
}

/** Guildbook's public source (AGPL-3.0); both footers link here. */
export const SOURCE_URL = "https://github.com/Guildbook/guildbook";

export const X_URL = "https://x.com/GuildbookIO";

/** Where users reach the Guildbook team (also in the terms and privacy policy). */
export const CONTACT_EMAIL = "matt.rosendin@gmail.com";

export const GUILDBOOK_DESCRIPTION =
  "Webs de hermandad para World of Warcraft: Forever. Plantillas, solicitudes, horarios de banda, progreso y análisis de registros de combate, en tu propio subdominio.";
