import { CREST_MANIFEST } from "@/lib/tabard/crest-manifest";

/**
 * Blizzard's guild tabard emblems (bundled under public/tabard by `pnpm emblems:fetch`). Blizzard gives them ids
 * only; the names and search words here are ours, for the admin picker.
 */
export interface CrestEmblem {
  id: number;
  name: string;
  tags: string[];
}

/** Names and search words by emblem id. Keep in step with the manifest (a test checks every id has one). */
const EMBLEM_NAMES: Record<number, [string, string?]> = {
  0: ["Corona de laurel", "laurel wreath victory leaves"],
  1: ["Gafas", "goggles engineer gnome"],
  2: ["Escarabajo", "beetle bug insect scarab"],
  3: ["Trébol de cuatro hojas", "four-leaf clover luck shamrock"],
  4: ["Trébol", "club cards suit"],
  5: ["Pica", "spade cards suit"],
  6: ["Corazón", "heart cards suit love"],
  7: ["Diamante", "diamond cards suit"],
  8: ["Rosa de los vientos", "compass rose star navigation"],
  9: ["Diadema", "coronet crown royal"],
  10: ["Corona abierta", "open crown royal"],
  11: ["Corona real", "royal crown king queen"],
  12: ["Águila bicéfala", "double-headed eagle bird griffin"],
  13: ["Lobos rampantes", "rampant wolves beasts pair"],
  14: ["Cara de león", "lion face cat beast"],
  15: ["Mariposa", "butterfly insect moth"],
  16: ["Ancla", "anchor sea ship sailor"],
  17: ["Barco", "ship sea sail boat"],
  18: ["Lis", "lily flower fleur-de-lis"],
  19: ["Hoja", "leaf plant herb"],
  20: ["Engranajes", "gears cog engineer"],
  21: ["Llama", "flame fire"],
  22: ["Martillo", "hammer warhammer smith"],
  23: ["Hacha de guerra", "battle axe weapon"],
  24: ["Calavera", "skull death bone"],
  25: ["Yelmo alado", "winged helm valkyrie warrior"],
  26: ["Bolsa de monedas", "coin purse gold money pouch"],
  27: ["Anillo", "ring band gold"],
  28: ["Pociones", "potions alchemy flask"],
  29: ["Yunque", "anvil smith forge"],
  30: ["Máscara", "mask masquerade rogue"],
  31: ["Ballesta", "crossbow bow hunter"],
  32: ["Libro abierto", "open book tome lore"],
  33: ["Gorro de bufón", "jester hat fool"],
  34: ["Árbol", "tree oak forest"],
  35: ["Cáliz", "chalice goblet grail cup"],
  36: ["Cobra", "cobra snake serpent"],
  37: ["Serpientes", "serpents snakes pair"],
  38: ["Escudo y espada", "shield and sword warrior defender"],
  39: ["Daga", "dagger blade knife rogue"],
  40: ["Calavera y dagas", "skull and daggers death rogue"],
  41: ["Tótem", "totem troll tiki"],
  42: ["Dragón alado", "wyvern dragon bat"],
  43: ["Demonio con cuernos", "horned demon fiend devil"],
  44: ["Carnero", "ram goat horns"],
  45: ["Botas", "boots travel"],
  46: ["Botas de piel", "fur boots winter"],
  47: ["Venera", "scallop shell sea pilgrim"],
  48: ["Ojos vigilantes", "watching eyes eyes"],
  49: ["Vela", "candle light wax"],
  50: ["Chistera", "top hat gentleman"],
  51: ["Farol", "lantern light hive"],
  52: ["Campana", "bell chime"],
  53: ["Candado", "padlock lock"],
  54: ["Sotuer", "saltire crossed bands x"],
  55: ["Tijeras", "scissors tailor"],
  56: ["Sombrero de mago", "wizard hat mage"],
  57: ["Caldero", "cauldron witch brew"],
  58: ["Montaña", "mountain peak"],
  59: ["Seta", "mushroom fungus"],
  60: ["Árbol muerto", "dead tree withered"],
  61: ["Nudo trébol", "trefoil knot triangle"],
  62: ["Estrella de pinchos", "spiked star throwing star snowflake"],
  63: ["Galón hacia abajo", "chevron down stripe"],
  64: ["Galón hacia arriba", "chevron up stripe"],
  65: ["Cucaracha", "cockroach bug insect"],
  66: ["Muslo asado", "drumstick meat food"],
  67: ["Magdalena", "muffin food cake"],
  68: ["Cuenco de sopa", "soup bowl food stew"],
  69: ["Oso rugiente", "roaring bear beast"],
  70: ["Costillar", "rib cage bones undead"],
  71: ["Espantapájaros", "scarecrow farm"],
  72: ["Naipes", "playing cards gamble"],
  73: ["Langosta", "lobster sea crustacean"],
  74: ["Margarita", "daisy flower"],
  75: ["Jarras de cerveza", "beer mugs ale tavern drink"],
  76: ["Llave", "key lock"],
  77: ["Cara de gato", "cat face kitty"],
  78: ["Mono", "monkey ape"],
  79: ["Gato contento", "content cat kitty"],
  80: ["Lagarto", "lizard salamander"],
  81: ["Llave inglesa", "wrench tool engineer"],
  82: ["Ojo", "eye watch"],
  83: ["Rueda", "wheel cart"],
  84: ["Murciélago", "bat night"],
  85: ["Reloj de arena", "hourglass time sand"],
  86: ["Veneno", "poison flask skull"],
  87: ["Ciervo", "stag deer antlers"],
  88: ["Bellota", "acorn oak nut"],
  89: ["Mojón de piedras", "cairn stones storm"],
  90: ["Pilas de monedas", "coin stacks gold money"],
  91: ["Búho", "owl bird wisdom"],
  92: ["Calavera y tibias", "skull and crossbones pirate death"],
  93: ["Antorcha", "torch fire light"],
  94: ["Lápida", "tombstone grave undead"],
  95: ["Gota de agua", "water drop rain"],
  96: ["Gema", "gem jewel diamond"],
  97: ["Cruz", "cross cross pattee holy"],
  98: ["Infinito", "infinity eternal"],
  99: ["Luna y estrellas", "moon and stars night crescent"],
  100: ["Sol radiante", "sunburst sun rays"],
  101: ["Huella de zarpa", "paw print pet beast"],
  102: ["Garra de oso", "bear claw beast"],
  103: ["Ojo de dragón", "dragon eye eye"],
  104: ["Espiral", "spiral vortex target"],
  105: ["Llamas viles", "fel flames fire"],
  106: ["Colmillos", "fangs jaws teeth"],
  107: ["Mano cornuda", "horned hand rock"],
  108: ["Puño", "fist strength"],
  109: ["Tablero de ajedrez", "checkerboard chess"],
  110: ["Hoja de arce", "maple leaf leaf"],
  111: ["Sol ardiente", "burning sun fire"],
  112: ["Árbol calcinado", "blasted tree fire"],
  113: ["Toro", "bull horns"],
  114: ["Pulpo", "octopus sea kraken"],
  115: ["Torre", "tower castle keep"],
  116: ["Mazos cruzados", "crossed mallets hammers"],
  117: ["Martillos de guerra cruzados", "crossed warhammers hammers"],
  118: ["Flechas cruzadas", "crossed arrows hunter"],
  119: ["Espadas cruzadas", "crossed swords blades"],
  120: ["Hachas cruzadas", "crossed axes axes"],
  121: ["Guadañas cruzadas", "crossed scythes sickles reaper"],
  122: ["Nudilleras de pinchos", "spiked knuckles brawler"],
  123: ["Guanteletes con garras", "clawed gauntlets claws"],
  124: ["Lucero del alba", "morning star mace"],
  125: ["Peón", "pawn chess"],
  126: ["Rayo", "lightning storm bolt"],
  127: ["Hongo nuclear", "mushroom cloud explosion"],
  128: ["León", "lion mane roar cat"],
  129: ["Gnomo", "gnome engineer"],
  130: ["Pino", "pine tree evergreen forest"],
  131: ["Dinamita", "dynamite explosives"],
  132: ["Telaraña", "spider web web"],
  133: ["Araña", "spider arachnid"],
  134: ["Copo de nieve", "snowflake ice frost winter"],
  135: ["Tortuga", "turtle tortoise"],
  136: ["Yeti", "yeti beast"],
  137: ["Pluma", "feather quill"],
  138: ["Figura encapuchada", "hooded figure cloak"],
  139: ["Bestia con cuernos", "horned beast claws"],
  140: ["Amuleto", "amulet necklace"],
  141: ["Serpientes gemelas", "twin serpents caduceus snakes"],
  142: ["Sombrero pirata", "pirate hat skull"],
  143: ["Pergamino", "scroll parchment"],
  144: ["Pergamino abierto", "open scroll parchment"],
  145: ["Conejo", "rabbit bunny hare"],
  146: ["Rana", "frog toad"],
  147: ["Huella", "footprint foot"],
  148: ["Barril", "barrel keg ale"],
  149: ["Hongo", "toadstool mushroom"],
  150: ["Omega", "omega horseshoe"],
  151: ["Herradura", "horseshoe luck"],
  152: ["Frasco", "flask potion"],
  153: ["Bestia peluda", "shaggy beast fur"],
  154: ["Estrella de mar", "starfish star sea"],
  155: ["Nubes", "clouds smoke swirl"],
  156: ["Lacería", "knotwork ornament"],
  157: ["Cara de piedra", "stone face statue"],
  158: ["Loto", "lotus flower"],
  159: ["Corazón alado", "winged heart heart"],
  160: ["León guardián", "guardian lion pandaren"],
  161: ["Máscara oni", "oni mask demon"],
  162: ["Guardián del templo", "temple guardian pandaren mask"],
  163: ["Cuernos tribales", "tribal horns sigil"],
  164: ["Sello con cuernos", "horned sigil tribal"],
  165: ["Calavera coronada", "crowned skull death"],
  166: ["Estrella del caos", "chaos star arrows"],
  167: ["Sonrisa demoníaca", "demon grin fiend"],
  168: ["Máscara de bestia", "beast mask wolf"],
  169: ["Calavera con cuernos", "horned skull bull"],
  170: ["Pícaro encapuchado", "hooded rogue assassin"],
  171: ["Nudo celta", "celtic knot triquetra"],
  172: ["Ornamento", "ornament sigil"],
  173: ["Fénix", "phoenix bird fire"],
  174: ["Goblin", "goblin gold money"],
  175: ["Cetro", "sceptre staff"],
  176: ["Trofeo", "trophy cup urn"],
  177: ["Calavera demoníaca", "demon skull death"],
  178: ["Flor", "blossom flower bud"],
  179: ["Arcoíris", "rainbow clouds"],
  180: ["Máscara tallada", "carved mask tribal"],
  181: ["Lobos y luna", "wolves and moon howl"],
  182: ["Vela derretida", "melted candle wax"],
  183: ["Sello octogonal", "octagon seal bagua"],
  184: ["Torre de ajedrez", "rook chess castle"],
  185: ["Regalo", "gift present"],
  186: ["Hombre de jengibre", "gingerbread man cookie"],
  187: ["Múrloc", "murloc fish"],
  188: ["Jarras", "tankards ale beer drink"],
  189: ["Alas", "wings angel"],
  190: ["Arañazos", "claw marks scratch"],
  191: ["Alas desplegadas", "swept wings feathers"],
  192: ["Calavera de dragón", "dragon skull dragon"],
  193: ["Lobo", "wolf howl beast pack"],
  194: ["Ojo del vidente", "seer's eye eye"],
  195: ["Runa", "rune sigil"],
};

export const CREST_EMBLEMS: readonly CrestEmblem[] = CREST_MANIFEST.emblems.map(({ id }) => {
  const [name, tags] = EMBLEM_NAMES[id] ?? [`Emblema ${id}`];
  return { id, name, tags: tags ? tags.split(" ") : [] };
});

const EMBLEM_IDS = new Set<number>(CREST_MANIFEST.emblems.map((e) => e.id));
const EMBLEM_SHA = new Map<number, string>(CREST_MANIFEST.emblems.map((e) => [e.id, e.sha]));

export const isCrestEmblem = (id: number | null | undefined): id is number => id != null && EMBLEM_IDS.has(id);
export const crestEmblem = (id: number) => CREST_EMBLEMS.find((e) => e.id === id);

/** Public URLs of the bundled masks, versioned by content so a refetched image busts caches. */
export const emblemSrc = (id: number) => `/tabard/emblems/${id}.png?v=${EMBLEM_SHA.get(id) ?? ""}`;
/** Paths under public/ for the server, which tints the masks itself. */
export const emblemFile = (id: number) => `tabard/emblems/${id}.png`;

/**
 * The closest Blizzard emblem to each drawn emblem guilds had before real emblems were bundled. Migration 0018 moved
 * every guild onto these (drizzle/0018_guild_crest.sql, kept in step by a test); anything else became the lion (128).
 */
export const LEGACY_EMBLEM_MATCH: Record<string, number> = {
  "cross-pattee": 97,
  cross: 97,
  "cross-fleury": 97,
  "celtic-cross": 171,
  sword: 39,
  "crossed-swords": 119,
  shield: 38,
  lion: 128,
  eagle: 12,
  dragon: 42,
  wolf: 193,
  skull: 24,
  tree: 34,
  sun: 100,
  moon: 99,
  star: 8,
  crown: 11,
  flame: 21,
  axe: 23,
  hammer: 22,
  bow: 31,
  anvil: 29,
  book: 32,
  raven: 91,
  "fleur-de-lis": 18,
  rose: 74,
  keys: 76,
  chalice: 35,
  tower: 115,
  griffin: 12,
};

