import type { RotationModel } from "./types";

/** Classic-era values; Forever may retune them once the beta log confirms ranks. */
export const protectionWarrior: RotationModel = {
  id: "warrior-protection",
  label: "Guerrero Protección",
  wowClass: "warrior",
  spec: "Protection",
  role: "tank",
  metric: "threat",
  resource: "rage",
  spells: [
    {
      key: "shield-slam",
      label: "Shield Slam",
      names: ["Shield Slam"],
      gcd: true,
      cooldownMs: 6000,
      cost: 20,
      threat: { bonus: [[40, 160], [48, 190], [54, 220], [60, 250]], on: "hit" },
      trackCooldown: true,
    },
    {
      key: "revenge",
      label: "Revenge",
      names: ["Revenge"],
      gcd: true,
      cooldownMs: 5000,
      cost: 5,
      threat: { bonus: [[14, 155], [24, 195], [34, 235], [44, 275], [54, 315], [60, 355]], on: "hit" },
      trackCooldown: true,
    },
    {
      key: "sunder",
      label: "Sunder Armor",
      names: ["Sunder Armor"],
      gcd: true,
      cost: 15,
      threat: { bonus: [[10, 100], [22, 140], [34, 180], [46, 220], [58, 260]], on: "cast" },
    },
    {
      key: "heroic-strike",
      label: "Heroic Strike",
      names: ["Heroic Strike"],
      gcd: false,
      nextSwing: true,
      cost: 15,
      threat: { bonus: [[1, 20], [8, 39], [16, 59], [24, 78], [32, 98], [40, 118], [48, 137], [56, 145], [60, 175]], on: "hit" },
    },
    { key: "shield-block", label: "Shield Block", names: ["Shield Block"], gcd: false, cooldownMs: 5000, cost: 10, trackCooldown: true },
    { key: "thunder-clap", label: "Thunder Clap", names: ["Thunder Clap"], gcd: true, cooldownMs: 4000, cost: 20, threat: { damageMultiplier: 2.5 } },
    { key: "battle-shout", label: "Battle Shout", names: ["Battle Shout"], gcd: true, cost: 10, threat: { bonus: [[1, 55]], on: "cast" } },
    { key: "demoralizing-shout", label: "Demoralizing Shout", names: ["Demoralizing Shout"], gcd: true, cost: 10, threat: { bonus: [[1, 43]], on: "cast" } },
    { key: "bloodrage", label: "Bloodrage", names: ["Bloodrage"], gcd: false, cooldownMs: 60_000, trackCooldown: true },
  ],
  auras: [
    { key: "shield-block", label: "Shield Block", names: ["Shield Block"], on: "player", scored: true, targetUptime: 0.6 },
    {
      key: "sunder",
      label: "Sunder Armor",
      names: ["Sunder Armor"],
      on: "target",
      scored: true,
      targetUptime: 0.9,
      appliedBy: "sunder",
      durationMs: 30_000,
      maxStacks: 5,
      anySource: true,
    },
    { key: "defensive-stance", label: "Defensive Stance", names: ["Defensive Stance"], on: "player" },
    { key: "battle-shout", label: "Battle Shout", names: ["Battle Shout"], on: "player" },
    { key: "demoralizing-shout", label: "Demoralizing Shout", names: ["Demoralizing Shout"], on: "target", anySource: true },
  ],
  procs: [{ key: "revenge", label: "Ventana de Revenge", spell: "revenge", windowMs: 5000, trigger: "avoided" }],
  priority: [
    { spell: "shield-slam", label: "Shield Slam en cuanto se recargue" },
    { spell: "revenge", label: "Revenge cuando se active", when: [{ kind: "procActive", proc: "revenge" }] },
    { spell: "sunder", label: "Sunder Armor hasta 5 acumulaciones", when: [{ kind: "stacksBelow", aura: "sunder", stacks: 5 }] },
    { spell: "sunder", label: "Sunder Armor de relleno" },
  ],
  threat: { stanceMultiplier: 1.3, stanceAura: "defensive-stance", perRageGained: 5, healingMultiplier: 0.5 },
  extras: ["rageDump", "swingContinuity"],
  rageDumpAt: 60,
  detect: ["shield-slam", "revenge", "shield-block", "sunder"],
  assumptions: [
    "La amenaza usa valores de Classic Era: Defensive Stance x1,3, amenaza adicional por rango de Sunder, Revenge, Shield Slam y Heroic Strike, 5 de amenaza por punto de ira de Bloodrage y la sanación a media amenaza.",
    "No se aplican los talentos que cambian la amenaza (Defiance, Improved Sunder).",
    "Si Defensive Stance no aparece nunca en el registro, se supone activa todo el combate.",
    "Revenge se puede usar durante 5 segundos después de esquivar, parar o bloquear un ataque hostil.",
  ],
};
